import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type LangCode = "EN" | "HI" | "MR";

const STORAGE_KEY = "agrolens_lang";

/* ─────────────────────────────────────────────────────────────
   TRANSLATION DICTIONARY
   ───────────────────────────────────────────────────────────── */

const dict: Record<LangCode, Record<string, string>> = {
  EN: {
    /* Header */
    "header.tagline": "AI Crop Intelligence",

    /* Sidebar */
    "nav.section.navigation": "Navigation",
    "nav.section.billing": "Plans & Billing",
    "nav.dashboard": "Dashboard",
    "nav.scan": "AI Scan",
    "nav.recommendations": "Recommendations",
    "nav.irrigation":      "Smart Irrigation",
    "nav.history": "Scan History",
    "nav.bhoomi": "Chat with BHOOMI",
    "nav.profile": "Profile",
    "nav.analytics": "Analytics",
    "nav.plans": "Pro Plans",
    "nav.billing": "Payment & Billing",
    "sidebar.upgradeTo": "Upgrade to Pro",
    "sidebar.upgradeFeatures": "Unlimited scans · BHOOMI voice · Treatment protocols",
    "sidebar.viewPlans": "View plans — from ₹79/mo →",
    "sidebar.signOut": "Sign Out",

    /* Auth — Login */
    "login.title": "Welcome back",
    "login.subtitle": "Sign in to your AgroLens account",
    "login.email": "Email Address",
    "login.emailPlaceholder": "farmer@example.com",
    "login.password": "Password",
    "login.forgotPassword": "Forgot Password?",
    "login.signIn": "Sign In",
    "login.tryDemo": "Try Demo Access",
    "login.newUser": "New to AgroLens?",
    "login.createAccount": "Create account",
    "login.or": "or",

    /* Auth — Register */
    "register.title": "Create your account",
    "register.subtitle": "Join AgroLens and start scanning crops",
    "register.fullName": "Full Name",
    "register.fullNamePlaceholder": "Ramesh Kumar",
    "register.email": "Email Address",
    "register.emailPlaceholder": "farmer@example.com",
    "register.password": "Password",
    "register.passwordPlaceholder": "Min. 6 characters",
    "register.farmerId": "Farmer ID",
    "register.farmerIdPlaceholder": "Optional — assigned by your Krishi Kendra",
    "register.submit": "Create Account",
    "register.alreadyHave": "Already have an account?",
    "register.signIn": "Sign in",
    "register.agreePrefix": "By creating an account, you agree to our",
    "register.terms": "Terms of Service",
    "register.and": "and",
    "register.privacy": "Privacy Policy",

    /* Dashboard */
    "dashboard.welcome": "Welcome back",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.scanCrop": "Scan Crop",
    "dashboard.scanCropDesc": "Upload photos for AI diagnosis",
    "dashboard.viewHistory": "View History",
    "dashboard.viewHistoryDesc": "Past scans & results",
    "dashboard.unlockPremium": "Unlock Premium",
    "dashboard.unlockPremiumDesc": "Full treatment protocols",
    "dashboard.chatBhoomi": "Chat with BHOOMI",
    "dashboard.chatBhoomiDesc": "Ask anything about your crops",
    "dashboard.recentScans": "Recent Scans",
    "dashboard.fieldHealth": "Field Health Overview",
    "dashboard.weeklyScans": "Weekly Scan Activity",
    "dashboard.aiRecommendations": "AI Recommendations",
    "dashboard.healthy": "Healthy",
    "dashboard.atRisk": "At Risk",
    "dashboard.diseased": "Diseased",
    "dashboard.unknown": "Unknown",
    "dashboard.today": "Today",
    "dashboard.yesterday": "Yesterday",
    "dashboard.viewAll": "View All",
    "dashboard.urgent": "Urgent",
    "dashboard.moderate": "Moderate",
    "dashboard.info": "Info",

    /* Weather */
    "weather.today": "Today's Weather",
    "weather.humidity": "Humidity",
    "weather.wind": "Wind",
    "weather.rain": "Rain",
    "weather.feelsLike": "Feels like",
    "weather.hourlyRain": "Hourly Rainfall",

    /* AI Scan */
    "scan.title": "AI Crop Scan",
    "scan.subtitle": "Upload 3 photos for accurate diagnosis",
    "scan.stepFields": "Field Info",
    "scan.stepPhotos": "Photos",
    "scan.stepAnalyse": "Analyse",
    "scan.cropType": "Crop Type",
    "scan.cropTypePlaceholder": "Select crop",
    "scan.soilType": "Soil Type",
    "scan.soilTypePlaceholder": "Select soil type",
    "scan.growthStage": "Growth Stage",
    "scan.growthStagePlaceholder": "Select stage",
    "scan.fieldName": "Field Name",
    "scan.fieldNamePlaceholder": "e.g. North Field A (optional)",
    "scan.photoWhole": "Whole Plant",
    "scan.photoLeaf": "Leaf Close-up",
    "scan.photoSoil": "Soil / Root",
    "scan.photoRequired": "Required",
    "scan.photoHint": "Tap or drag to upload",
    "scan.analyseButton": "Analyse Crop",
    "scan.missingFields": "Please complete the following before scanning:",
    "scan.processing": "Analysing your crop...",

    /* Scan Result */
    "result.primaryDiagnosis": "Primary Diagnosis",
    "result.secondaryDiagnosis": "Secondary Possibility",
    "result.confidence": "Confidence",
    "result.severity": "Severity",
    "result.cause": "Cause",
    "result.affectedArea": "Affected Area",
    "result.spreadRate": "Spread Rate",
    "result.estimatedLoss": "Estimated Loss",
    "result.treatmentWindow": "Treatment Window",
    "result.quickFix": "Quick Fix",
    "result.expandDetails": "Expand details",
    "result.collapseDetails": "Collapse",
    "result.unlockFull": "Unlock Full Recommendations",
    "result.unlockSubtitle": "Get complete treatment protocol, fertilizer dosage, and organic alternatives",
    "result.photosUploaded": "Photos Uploaded",

    /* Recommendations */
    "reco.title": "Premium Recommendations",
    "reco.treatment": "Treatment Protocol",
    "reco.fertilizer": "Fertilizer Dosage Plan",
    "reco.organic": "Organic Alternatives",
    "reco.application": "Application Methods",
    "reco.historicalData": "Historical Disease Occurrence",
    "reco.pesticide": "Pesticide Guidance",
    "reco.preventive": "Preventive Care",
    "reco.dosage": "Dosage Guide",
    "reco.irrigation": "Irrigation Advice",
    "reco.risk": "Risk Level",
    "reco.organic.badge": "Zero Chemical",
    "reco.recommended": "Recommended",

    /* History */
    "history.title": "Scan History",
    "history.searchPlaceholder": "Search scans by crop, field, disease...",
    "history.noResults": "No scans found",
    "history.noResultsHint": "Try a different search term or filter",
    "history.filterAll": "All",
    "history.filterHigh": "High Severity",
    "history.filterMedium": "Medium",
    "history.filterLow": "Low / Healthy",
    "history.totalScans": "Total Scans",
    "history.thisMonth": "This Month",

    /* Subscription / Pricing */
    "sub.title": "Choose Your Plan",
    "sub.subtitle": "Unlock the full power of AI farming intelligence",
    "sub.unlock": "Unlock AgroLens Pro",
    "sub.unlockDesc": "Get the full power of AI crop intelligence — unlimited scans, BHOOMI assistant, and expert treatment protocols.",
    "sub.monthly": "Monthly",
    "sub.yearly": "Yearly",
    "sub.monthly.desc": "Perfect for trying out AgroLens Pro.",
    "sub.yearly.desc": "For serious farmers — maximum savings.",
    "sub.yearly.period": "/year",
    "sub.save": "Save 10%",
    "sub.bestValue": "Best Value",
    "sub.getStarted": "Get Started",
    "sub.currentPlan": "Current Plan",
    "sub.popular": "Most Popular",
    "sub.perMonth": "/month",
    "sub.billedYearly": "billed yearly",
    "sub.effective": "effectively",
    "sub.flexible": "Flexible",
    "sub.everything": "Everything included",
    "sub.trial": "7-day free trial · No questions asked cancellation",
    "sub.continueTo": "Continue to Payment",
    "sub.cancelAnytime": "Cancel anytime",
    "sub.secure": "Secure payment",
    "sub.farmers": "50K+ farmers",
    "sub.madeInIndia": "Made in India",
    "sub.unlimited": "Unlimited",
    "sub.feature": "Feature",
    "sub.free": "Free",
    "sub.pro": "Pro",
    "sub.comp.scans": "AI Scans",
    "sub.comp.bhoomi": "BHOOMI Voice",
    "sub.comp.protocols": "Full Protocols",
    "sub.comp.expert": "Expert Help",
    /* Feature list items */
    "sub.feat.scans": "Unlimited AI crop scans",
    "sub.feat.bhoomi": "BHOOMI voice assistant (24/7)",
    "sub.feat.protocols": "Full premium treatment protocols",
    "sub.feat.fertilizer": "Fertilizer & dosage plans",
    "sub.feat.history": "Historical disease insights",
    "sub.feat.weather": "Weather-based spray advisories",
    "sub.feat.market": "Market price & mandi alerts",
    "sub.feat.support": "Priority support (< 2 hour response)",
    "sub.feat.offline": "Offline scan mode",
    "sub.feat.multifield": "Multi-field management",

    /* Checkout */
    "checkout.title": "Complete Payment",
    "checkout.success": "Payment Successful!",
    "checkout.successMsg": "Your Pro subscription is now active.",
    "checkout.welcomePro": "Welcome to AgroLens Pro. Your account has been upgraded instantly.",
    "checkout.payNow": "Pay Now",
    "checkout.paySecurely": "Pay ₹849 Securely",
    "checkout.processing": "Processing Payment…",
    "checkout.backToPlans": "Back to Plans",
    "checkout.secureCheckout": "Secure Checkout",
    "checkout.ssl": "256-bit SSL encrypted · Powered by Razorpay",
    "checkout.paymentMethod": "Payment Method",
    "checkout.plan": "Plan",
    "checkout.amountPaid": "Amount paid",
    "checkout.validUntil": "Valid until",
    "checkout.transactionId": "Transaction ID",
    "checkout.goToDashboard": "Go to Dashboard",
    "checkout.upi": "UPI",
    "checkout.card": "Credit / Debit Card",
    "checkout.wallet": "Wallet",

    /* BHOOMI */
    "bhoomi.online": "Online",
    "bhoomi.listening": "Listening… speak now",
    "bhoomi.placeholder": "Ask BHOOMI anything…",
    "bhoomi.voiceHint": "Speak in Hindi, Marathi, English · Voice nav enabled",
    "bhoomi.noMic": "Voice input is not supported in your browser. Please type your question instead.",
    "bhoomi.micError": "I couldn't catch that. Please speak clearly or type your question.",

    /* Common */
    "common.loading": "Loading...",
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.viewAll": "View All",
    "common.learnMore": "Learn More",
    "common.perMonth": "per month",
  },

  HI: {
    /* Header */
    "header.tagline": "AI फसल बुद्धिमत्ता",

    /* Sidebar */
    "nav.section.navigation": "नेविगेशन",
    "nav.section.billing": "योजनाएं और बिलिंग",
    "nav.dashboard": "डैशबोर्ड",
    "nav.scan": "AI स्कैन",
    "nav.recommendations": "सुझाव",
    "nav.irrigation":      "स्मार्ट सिंचाई",
    "nav.history": "स्कैन इतिहास",
    "nav.bhoomi": "BHOOMI से चैट करें",
    "nav.profile": "प्रोफ़ाइल",
    "nav.analytics": "एनालिटिक्स",
    "nav.plans": "प्रो योजनाएं",
    "nav.billing": "भुगतान और बिलिंग",
    "sidebar.upgradeTo": "प्रो में अपग्रेड करें",
    "sidebar.upgradeFeatures": "असीमित स्कैन · BHOOMI वॉइस · उपचार प्रोटोकॉल",
    "sidebar.viewPlans": "योजनाएं देखें — ₹79/माह से →",
    "sidebar.signOut": "साइन आउट",

    /* Auth — Login */
    "login.title": "वापस स्वागत है",
    "login.subtitle": "अपने AgroLens खाते में साइन इन करें",
    "login.email": "ईमेल पता",
    "login.emailPlaceholder": "farmer@example.com",
    "login.password": "पासवर्ड",
    "login.forgotPassword": "पासवर्ड भूल गए?",
    "login.signIn": "साइन इन करें",
    "login.tryDemo": "डेमो एक्सेस आज़माएं",
    "login.newUser": "AgroLens में नए हैं?",
    "login.createAccount": "खाता बनाएं",
    "login.or": "या",

    /* Auth — Register */
    "register.title": "अपना खाता बनाएं",
    "register.subtitle": "AgroLens से जुड़ें और फसल स्कैन शुरू करें",
    "register.fullName": "पूरा नाम",
    "register.fullNamePlaceholder": "रमेश कुमार",
    "register.email": "ईमेल पता",
    "register.emailPlaceholder": "farmer@example.com",
    "register.password": "पासवर्ड",
    "register.passwordPlaceholder": "कम से कम 6 अक्षर",
    "register.farmerId": "किसान आईडी",
    "register.farmerIdPlaceholder": "वैकल्पिक — कृषि केंद्र द्वारा दी गई",
    "register.submit": "खाता बनाएं",
    "register.alreadyHave": "पहले से खाता है?",
    "register.signIn": "साइन इन करें",
    "register.agreePrefix": "खाता बनाकर आप हमारी",
    "register.terms": "सेवा शर्तों",
    "register.and": "और",
    "register.privacy": "गोपनीयता नीति",

    /* Dashboard */
    "dashboard.welcome": "वापस स्वागत है",
    "dashboard.quickActions": "त्वरित कार्य",
    "dashboard.scanCrop": "फसल स्कैन करें",
    "dashboard.scanCropDesc": "AI निदान के लिए फ़ोटो अपलोड करें",
    "dashboard.viewHistory": "इतिहास देखें",
    "dashboard.viewHistoryDesc": "पिछले स्कैन और परिणाम",
    "dashboard.unlockPremium": "प्रीमियम अनलॉक करें",
    "dashboard.unlockPremiumDesc": "पूर्ण उपचार प्रोटोकॉल",
    "dashboard.chatBhoomi": "BHOOMI से चैट करें",
    "dashboard.chatBhoomiDesc": "अपनी फसल के बारे में कुछ भी पूछें",
    "dashboard.recentScans": "हाल के स्कैन",
    "dashboard.fieldHealth": "खेत स्वास्थ्य अवलोकन",
    "dashboard.weeklyScans": "साप्ताहिक स्कैन गतिविधि",
    "dashboard.aiRecommendations": "AI सुझाव",
    "dashboard.healthy": "स्वस्थ",
    "dashboard.atRisk": "जोखिम में",
    "dashboard.diseased": "रोगग्रस्त",
    "dashboard.unknown": "अज्ञात",
    "dashboard.today": "आज",
    "dashboard.yesterday": "कल",
    "dashboard.viewAll": "सभी देखें",
    "dashboard.urgent": "अत्यावश्यक",
    "dashboard.moderate": "मध्यम",
    "dashboard.info": "जानकारी",

    /* Weather */
    "weather.today": "आज का मौसम",
    "weather.humidity": "आर्द्रता",
    "weather.wind": "हवा",
    "weather.rain": "वर्षा",
    "weather.feelsLike": "महसूस होता है",
    "weather.hourlyRain": "प्रति घंटा वर्षा",

    /* AI Scan */
    "scan.title": "AI फसल स्कैन",
    "scan.subtitle": "सटीक निदान के लिए 3 तस्वीरें अपलोड करें",
    "scan.stepFields": "खेत की जानकारी",
    "scan.stepPhotos": "तस्वीरें",
    "scan.stepAnalyse": "विश्लेषण",
    "scan.cropType": "फसल का प्रकार",
    "scan.cropTypePlaceholder": "फसल चुनें",
    "scan.soilType": "मिट्टी का प्रकार",
    "scan.soilTypePlaceholder": "मिट्टी का प्रकार चुनें",
    "scan.growthStage": "विकास चरण",
    "scan.growthStagePlaceholder": "चरण चुनें",
    "scan.fieldName": "खेत का नाम",
    "scan.fieldNamePlaceholder": "जैसे उत्तरी खेत A (वैकल्पिक)",
    "scan.photoWhole": "पूरा पौधा",
    "scan.photoLeaf": "पत्ती क्लोज़-अप",
    "scan.photoSoil": "मिट्टी / जड़",
    "scan.photoRequired": "आवश्यक",
    "scan.photoHint": "टैप करें या खींचें",
    "scan.analyseButton": "फसल का विश्लेषण करें",
    "scan.missingFields": "स्कैन करने से पहले निम्नलिखित पूरा करें:",
    "scan.processing": "आपकी फसल का विश्लेषण हो रहा है...",

    /* Scan Result */
    "result.primaryDiagnosis": "प्राथमिक निदान",
    "result.secondaryDiagnosis": "द्वितीयक संभावना",
    "result.confidence": "आत्मविश्वास",
    "result.severity": "गंभीरता",
    "result.cause": "कारण",
    "result.affectedArea": "प्रभावित क्षेत्र",
    "result.spreadRate": "फैलाव दर",
    "result.estimatedLoss": "अनुमानित नुकसान",
    "result.treatmentWindow": "उपचार अवधि",
    "result.quickFix": "त्वरित उपाय",
    "result.expandDetails": "विस्तार देखें",
    "result.collapseDetails": "संकुचित करें",
    "result.unlockFull": "पूर्ण सुझाव अनलॉक करें",
    "result.unlockSubtitle": "पूर्ण उपचार प्रोटोकॉल, उर्वरक मात्रा, और जैविक विकल्प पाएं",
    "result.photosUploaded": "अपलोड की गई तस्वीरें",

    /* Recommendations */
    "reco.title": "प्रीमियम सुझाव",
    "reco.treatment": "उपचार प्रोटोकॉल",
    "reco.fertilizer": "उर्वरक मात्रा योजना",
    "reco.organic": "जैविक विकल्प",
    "reco.application": "प्रयोग विधियां",
    "reco.historicalData": "ऐतिहासिक रोग घटना",
    "reco.pesticide": "कीटनाशक मार्गदर्शन",
    "reco.preventive": "निवारक देखभाल",
    "reco.dosage": "खुराक मार्गदर्शिका",
    "reco.irrigation": "सिंचाई सलाह",
    "reco.risk": "जोखिम स्तर",
    "reco.organic.badge": "शून्य रासायनिक",
    "reco.recommended": "अनुशंसित",

    /* History */
    "history.title": "स्कैन इतिहास",
    "history.searchPlaceholder": "फसल, खेत, रोग से खोजें...",
    "history.noResults": "कोई स्कैन नहीं मिला",
    "history.noResultsHint": "कोई अन्य खोज शब्द या फ़िल्टर आज़माएं",
    "history.filterAll": "सभी",
    "history.filterHigh": "उच्च गंभीरता",
    "history.filterMedium": "मध्यम",
    "history.filterLow": "कम / स्वस्थ",
    "history.totalScans": "कुल स्कैन",
    "history.thisMonth": "इस महीने",

    /* Subscription */
    "sub.title": "अपनी योजना चुनें",
    "sub.subtitle": "AI कृषि बुद्धिमत्ता की पूरी शक्ति अनलॉक करें",
    "sub.unlock": "AgroLens Pro अनलॉक करें",
    "sub.unlockDesc": "AI फसल बुद्धिमत्ता की पूरी शक्ति पाएं — असीमित स्कैन, BHOOMI सहायक, और विशेषज्ञ उपचार प्रोटोकॉल।",
    "sub.monthly": "मासिक",
    "sub.yearly": "वार्षिक",
    "sub.monthly.desc": "AgroLens Pro आज़माने के लिए परफेक्ट।",
    "sub.yearly.desc": "गंभीर किसानों के लिए — अधिकतम बचत।",
    "sub.yearly.period": "/वर्ष",
    "sub.save": "10% बचाएं",
    "sub.bestValue": "सर्वोत्तम मूल्य",
    "sub.getStarted": "शुरू करें",
    "sub.currentPlan": "वर्तमान योजना",
    "sub.popular": "सबसे लोकप्रिय",
    "sub.perMonth": "/माह",
    "sub.billedYearly": "वार्षिक बिल",
    "sub.effective": "प्रभावी रूप से",
    "sub.flexible": "लचीला",
    "sub.everything": "सब कुछ शामिल",
    "sub.trial": "7 दिन का निःशुल्क ट्रायल · बिना सवाल रद्दीकरण",
    "sub.continueTo": "भुगतान के लिए जारी रखें",
    "sub.cancelAnytime": "कभी भी रद्द करें",
    "sub.secure": "सुरक्षित भुगतान",
    "sub.farmers": "50K+ किसान",
    "sub.madeInIndia": "भारत में निर्मित",
    "sub.unlimited": "असीमित",
    "sub.feature": "सुविधा",
    "sub.free": "निःशुल्क",
    "sub.pro": "प्रो",
    "sub.comp.scans": "AI स्कैन",
    "sub.comp.bhoomi": "BHOOMI वॉइस",
    "sub.comp.protocols": "पूर्ण प्रोटोकॉल",
    "sub.comp.expert": "विशेषज्ञ सहायता",
    "sub.feat.scans": "असीमित AI फसल स्कैन",
    "sub.feat.bhoomi": "BHOOMI वॉइस सहायक (24/7)",
    "sub.feat.protocols": "पूर्ण प्रीमियम उपचार प्रोटोकॉल",
    "sub.feat.fertilizer": "उर्वरक और खुराक योजनाएं",
    "sub.feat.history": "ऐतिहासिक रोग अंतर्दृष्टि",
    "sub.feat.weather": "मौसम-आधारित स्प्रे सलाह",
    "sub.feat.market": "बाजार मूल्य और मंडी अलर्ट",
    "sub.feat.support": "प्राथमिकता समर्थन (< 2 घंटे)",
    "sub.feat.offline": "ऑफलाइन स्कैन मोड",
    "sub.feat.multifield": "बहु-खेत प्रबंधन",

    /* Checkout */
    "checkout.title": "भुगतान पूरा करें",
    "checkout.success": "भुगतान सफल!",
    "checkout.successMsg": "आपकी प्रो सदस्यता अब सक्रिय है।",
    "checkout.welcomePro": "AgroLens Pro में आपका स्वागत है। आपका खाता तुरंत अपग्रेड हो गया है।",
    "checkout.payNow": "अभी भुगतान करें",
    "checkout.paySecurely": "₹849 सुरक्षित रूप से भुगतान करें",
    "checkout.processing": "भुगतान प्रक्रिया में…",
    "checkout.backToPlans": "योजनाओं पर वापस जाएं",
    "checkout.secureCheckout": "सुरक्षित चेकआउट",
    "checkout.ssl": "256-बिट SSL एन्क्रिप्टेड · Razorpay द्वारा संचालित",
    "checkout.paymentMethod": "भुगतान विधि",
    "checkout.plan": "योजना",
    "checkout.amountPaid": "भुगतान की गई राशि",
    "checkout.validUntil": "तक वैध",
    "checkout.transactionId": "लेनदेन ID",
    "checkout.goToDashboard": "डैशबोर्ड पर जाएं",
    "checkout.upi": "UPI",
    "checkout.card": "क्रेडिट / डेबिट कार्ड",
    "checkout.wallet": "वॉलेट",

    /* BHOOMI */
    "bhoomi.online": "ऑनलाइन",
    "bhoomi.listening": "सुन रहा हूं… अभी बोलें",
    "bhoomi.placeholder": "BHOOMI से कुछ भी पूछें…",
    "bhoomi.voiceHint": "हिन्दी, मराठी, अंग्रेज़ी में बोलें · वॉइस नेव सक्षम",
    "bhoomi.noMic": "आपके ब्राउज़र में वॉइस इनपुट समर्थित नहीं है। कृपया टाइप करें।",
    "bhoomi.micError": "मैं समझ नहीं पाया। कृपया स्पष्ट रूप से बोलें या टाइप करें।",

    /* Common */
    "common.loading": "लोड हो रहा है...",
    "common.back": "वापस",
    "common.save": "सेव करें",
    "common.cancel": "रद्द करें",
    "common.submit": "जमा करें",
    "common.close": "बंद करें",
    "common.viewAll": "सभी देखें",
    "common.learnMore": "और जानें",
    "common.perMonth": "प्रति माह",
  },

  MR: {
    /* Header */
    "header.tagline": "AI पीक बुद्धिमत्ता",

    /* Sidebar */
    "nav.section.navigation": "नेव्हिगेशन",
    "nav.section.billing": "योजना आणि बिलिंग",
    "nav.dashboard": "डॅशबोर्ड",
    "nav.scan": "AI स्कॅन",
    "nav.recommendations": "शिफारसी",
    "nav.irrigation":      "स्मार्ट सिंचन",
    "nav.history": "स्कॅन इतिहास",
    "nav.bhoomi": "भूमीशी चॅट करा",
    "nav.profile": "प्रोफाइल",
    "nav.analytics": "अ‍ॅनलिटिक्स",
    "nav.plans": "प्रो योजना",
    "nav.billing": "पेमेंट आणि बिलिंग",
    "sidebar.upgradeTo": "प्रोमध्ये अपग्रेड करा",
    "sidebar.upgradeFeatures": "अमर्यादित स्कॅन · BHOOMI व्हॉइस · उपचार प्रोटोकॉल",
    "sidebar.viewPlans": "योजना पाहा — ₹79/महिना पासून →",
    "sidebar.signOut": "साइन आउट करा",

    /* Auth — Login */
    "login.title": "परत स्वागत आहे",
    "login.subtitle": "आपल्या AgroLens खात्यात साइन इन करा",
    "login.email": "ईमेल पत्ता",
    "login.emailPlaceholder": "farmer@example.com",
    "login.password": "पासवर्ड",
    "login.forgotPassword": "पासवर्ड विसरलात?",
    "login.signIn": "साइन इन करा",
    "login.tryDemo": "डेमो ऍक्सेस वापरून पाहा",
    "login.newUser": "AgroLens साठी नवीन आहात?",
    "login.createAccount": "खाते तयार करा",
    "login.or": "किंवा",

    /* Auth — Register */
    "register.title": "आपले खाते तयार करा",
    "register.subtitle": "AgroLens मध्ये सामील व्हा आणि पीक स्कॅन सुरू करा",
    "register.fullName": "पूर्ण नाव",
    "register.fullNamePlaceholder": "रमेश कुमार",
    "register.email": "ईमेल पत्ता",
    "register.emailPlaceholder": "farmer@example.com",
    "register.password": "पासवर्ड",
    "register.passwordPlaceholder": "किमान 6 अक्षरे",
    "register.farmerId": "शेतकरी ID",
    "register.farmerIdPlaceholder": "पर्यायी — कृषी केंद्राने दिलेली",
    "register.submit": "खाते तयार करा",
    "register.alreadyHave": "आधीच खाते आहे?",
    "register.signIn": "साइन इन करा",
    "register.agreePrefix": "खाते तयार करून तुम्ही आमच्या",
    "register.terms": "सेवा अटी",
    "register.and": "आणि",
    "register.privacy": "गोपनीयता धोरण",

    /* Dashboard */
    "dashboard.welcome": "परत स्वागत आहे",
    "dashboard.quickActions": "त्वरित कृती",
    "dashboard.scanCrop": "पीक स्कॅन करा",
    "dashboard.scanCropDesc": "AI निदानासाठी फोटो अपलोड करा",
    "dashboard.viewHistory": "इतिहास पाहा",
    "dashboard.viewHistoryDesc": "मागील स्कॅन आणि निकाल",
    "dashboard.unlockPremium": "प्रीमियम अनलॉक करा",
    "dashboard.unlockPremiumDesc": "संपूर्ण उपचार प्रोटोकॉल",
    "dashboard.chatBhoomi": "भूमीशी चॅट करा",
    "dashboard.chatBhoomiDesc": "तुमच्या पिकाबद्दल काहीही विचारा",
    "dashboard.recentScans": "अलीकडील स्कॅन",
    "dashboard.fieldHealth": "शेत आरोग्य आढावा",
    "dashboard.weeklyScans": "साप्ताहिक स्कॅन क्रियाकलाप",
    "dashboard.aiRecommendations": "AI शिफारसी",
    "dashboard.healthy": "निरोगी",
    "dashboard.atRisk": "धोक्यात",
    "dashboard.diseased": "रोगग्रस्त",
    "dashboard.unknown": "अज्ञात",
    "dashboard.today": "आज",
    "dashboard.yesterday": "काल",
    "dashboard.viewAll": "सर्व पाहा",
    "dashboard.urgent": "तातडीचे",
    "dashboard.moderate": "मध्यम",
    "dashboard.info": "माहिती",

    /* Weather */
    "weather.today": "आजचे हवामान",
    "weather.humidity": "आर्द्रता",
    "weather.wind": "वारा",
    "weather.rain": "पाऊस",
    "weather.feelsLike": "जाणवते",
    "weather.hourlyRain": "तासावार पाऊस",

    /* AI Scan */
    "scan.title": "AI पीक स्कॅन",
    "scan.subtitle": "अचूक निदानासाठी 3 फोटो अपलोड करा",
    "scan.stepFields": "शेत माहिती",
    "scan.stepPhotos": "फोटो",
    "scan.stepAnalyse": "विश्लेषण",
    "scan.cropType": "पीक प्रकार",
    "scan.cropTypePlaceholder": "पीक निवडा",
    "scan.soilType": "माती प्रकार",
    "scan.soilTypePlaceholder": "माती प्रकार निवडा",
    "scan.growthStage": "वाढीचा टप्पा",
    "scan.growthStagePlaceholder": "टप्पा निवडा",
    "scan.fieldName": "शेत नाव",
    "scan.fieldNamePlaceholder": "उदा. उत्तर शेत A (पर्यायी)",
    "scan.photoWhole": "संपूर्ण झाड",
    "scan.photoLeaf": "पान क्लोज-अप",
    "scan.photoSoil": "माती / मूळ",
    "scan.photoRequired": "आवश्यक",
    "scan.photoHint": "टॅप करा किंवा ड्रॅग करा",
    "scan.analyseButton": "पीक विश्लेषण करा",
    "scan.missingFields": "स्कॅन करण्यापूर्वी हे पूर्ण करा:",
    "scan.processing": "तुमच्या पिकाचे विश्लेषण होत आहे...",

    /* Scan Result */
    "result.primaryDiagnosis": "प्राथमिक निदान",
    "result.secondaryDiagnosis": "दुय्यम शक्यता",
    "result.confidence": "आत्मविश्वास",
    "result.severity": "तीव्रता",
    "result.cause": "कारण",
    "result.affectedArea": "प्रभावित क्षेत्र",
    "result.spreadRate": "प्रसार दर",
    "result.estimatedLoss": "अंदाजित नुकसान",
    "result.treatmentWindow": "उपचार कालावधी",
    "result.quickFix": "त्वरित उपाय",
    "result.expandDetails": "तपशील पाहा",
    "result.collapseDetails": "संकुचित करा",
    "result.unlockFull": "संपूर्ण शिफारसी अनलॉक करा",
    "result.unlockSubtitle": "संपूर्ण उपचार प्रोटोकॉल, खत मात्रा आणि सेंद्रिय पर्याय मिळवा",
    "result.photosUploaded": "अपलोड केलेले फोटो",

    /* Recommendations */
    "reco.title": "प्रीमियम शिफारसी",
    "reco.treatment": "उपचार प्रोटोकॉल",
    "reco.fertilizer": "खत मात्रा योजना",
    "reco.organic": "सेंद्रिय पर्याय",
    "reco.application": "वापर पद्धती",
    "reco.historicalData": "ऐतिहासिक रोग घटना",
    "reco.pesticide": "कीटकनाशक मार्गदर्शन",
    "reco.preventive": "प्रतिबंधात्मक काळजी",
    "reco.dosage": "मात्रा मार्गदर्शिका",
    "reco.irrigation": "सिंचन सल्ला",
    "reco.risk": "धोका पातळी",
    "reco.organic.badge": "शून्य रासायनिक",
    "reco.recommended": "शिफारस केलेले",

    /* History */
    "history.title": "स्कॅन इतिहास",
    "history.searchPlaceholder": "पीक, शेत, रोगाने शोधा...",
    "history.noResults": "कोणते स्कॅन सापडले नाहीत",
    "history.noResultsHint": "वेगळा शोध शब्द किंवा फिल्टर वापरून पाहा",
    "history.filterAll": "सर्व",
    "history.filterHigh": "उच्च तीव्रता",
    "history.filterMedium": "मध्यम",
    "history.filterLow": "कमी / निरोगी",
    "history.totalScans": "एकूण स्कॅन",
    "history.thisMonth": "या महिन्यात",

    /* Subscription */
    "sub.title": "आपली योजना निवडा",
    "sub.subtitle": "AI शेती बुद्धिमत्तेची संपूर्ण शक्ती अनलॉक करा",
    "sub.unlock": "AgroLens Pro अनलॉक करा",
    "sub.unlockDesc": "AI पीक बुद्धिमत्तेची संपूर्ण शक्ती मिळवा — अमर्यादित स्कॅन, BHOOMI सहाय्यक, आणि तज्ज्ञ उपचार प्रोटोकॉल.",
    "sub.monthly": "मासिक",
    "sub.yearly": "वार्षिक",
    "sub.monthly.desc": "AgroLens Pro वापरून पाहण्यासाठी उत्तम.",
    "sub.yearly.desc": "गंभीर शेतकऱ्यांसाठी — जास्तीत जास्त बचत.",
    "sub.yearly.period": "/वर्ष",
    "sub.save": "10% बचत",
    "sub.bestValue": "सर्वोत्तम मूल्य",
    "sub.getStarted": "सुरू करा",
    "sub.currentPlan": "सध्याची योजना",
    "sub.popular": "सर्वात लोकप्रिय",
    "sub.perMonth": "/महिना",
    "sub.billedYearly": "वार्षिक बिल",
    "sub.effective": "प्रभावीपणे",
    "sub.flexible": "लवचिक",
    "sub.everything": "सर्व काही समाविष्ट",
    "sub.trial": "7 दिवस विनामूल्य ट्रायल · कोणत्याही प्रश्नाशिवाय रद्दीकरण",
    "sub.continueTo": "पेमेंटसाठी पुढे जा",
    "sub.cancelAnytime": "कधीही रद्द करा",
    "sub.secure": "सुरक्षित पेमेंट",
    "sub.farmers": "50K+ शेतकरी",
    "sub.madeInIndia": "भारतात बनवलेले",
    "sub.unlimited": "अमर्यादित",
    "sub.feature": "वैशिष्ट्य",
    "sub.free": "विनामूल्य",
    "sub.pro": "प्रो",
    "sub.comp.scans": "AI स्कॅन",
    "sub.comp.bhoomi": "BHOOMI व्हॉइस",
    "sub.comp.protocols": "संपूर्ण प्रोटोकॉल",
    "sub.comp.expert": "तज्ज्ञ मदत",
    "sub.feat.scans": "अमर्यादित AI पीक स्कॅन",
    "sub.feat.bhoomi": "BHOOMI व्हॉइस सहाय्यक (24/7)",
    "sub.feat.protocols": "संपूर्ण प्रीमियम उपचार प्रोटोकॉल",
    "sub.feat.fertilizer": "खत आणि मात्रा योजना",
    "sub.feat.history": "ऐतिहासिक रोग माहिती",
    "sub.feat.weather": "हवामान-आधारित फवारणी सल्ला",
    "sub.feat.market": "बाजारभाव आणि मंडी अलर्ट",
    "sub.feat.support": "प्राधान्य समर्थन (< 2 तास)",
    "sub.feat.offline": "ऑफलाइन स्कॅन मोड",
    "sub.feat.multifield": "बहु-शेत व्यवस्थापन",

    /* Checkout */
    "checkout.title": "पेमेंट पूर्ण करा",
    "checkout.success": "पेमेंट यशस्वी!",
    "checkout.successMsg": "तुमची प्रो सदस्यता आता सक्रिय आहे.",
    "checkout.welcomePro": "AgroLens Pro मध्ये आपले स्वागत आहे. तुमचे खाते त्वरित अपग्रेड झाले आहे.",
    "checkout.payNow": "आता पेमेंट करा",
    "checkout.paySecurely": "₹849 सुरक्षितपणे पेमेंट करा",
    "checkout.processing": "पेमेंट प्रक्रिया सुरू आहे…",
    "checkout.backToPlans": "योजनांकडे परत जा",
    "checkout.secureCheckout": "सुरक्षित चेकआउट",
    "checkout.ssl": "256-बिट SSL एन्क्रिप्टेड · Razorpay द्वारे संचालित",
    "checkout.paymentMethod": "पेमेंट पद्धत",
    "checkout.plan": "योजना",
    "checkout.amountPaid": "भरलेली रक्कम",
    "checkout.validUntil": "पर्यंत वैध",
    "checkout.transactionId": "व्यवहार ID",
    "checkout.goToDashboard": "डॅशबोर्डवर जा",
    "checkout.upi": "UPI",
    "checkout.card": "क्रेडिट / डेबिट कार्ड",
    "checkout.wallet": "वॉलेट",

    /* BHOOMI */
    "bhoomi.online": "ऑनलाइन",
    "bhoomi.listening": "ऐकत आहे… आता बोला",
    "bhoomi.placeholder": "BHOOMI ला काहीही विचारा…",
    "bhoomi.voiceHint": "मराठी, हिंदी, इंग्रजीत बोला · व्हॉइस नेव्हिगेशन सक्षम",
    "bhoomi.noMic": "तुमच्या ब्राउझरमध्ये व्हॉइस इनपुट समर्थित नाही. कृपया टाइप करा.",
    "bhoomi.micError": "मला समजले नाही. कृपया स्पष्टपणे बोला किंवा टाइप करा.",

    /* Common */
    "common.loading": "लोड होत आहे...",
    "common.back": "मागे",
    "common.save": "जतन करा",
    "common.cancel": "रद्द करा",
    "common.submit": "सबमिट करा",
    "common.close": "बंद करा",
    "common.viewAll": "सर्व पाहा",
    "common.learnMore": "अधिक जाणून घ्या",
    "common.perMonth": "प्रति महिना",
  },
};

/* ─────────────────────────────────────────────────────────────
   CONTEXT
   ───────────────────────────────────────────────────────────── */

interface LanguageContextValue {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as LangCode | null;
      return saved && ["EN", "HI", "MR"].includes(saved) ? saved : "EN";
    } catch {
      return "EN";
    }
  });

  const setLang = useCallback((code: LangCode) => {
    try { localStorage.setItem(STORAGE_KEY, code); } catch {}
    setLangState(code);
  }, []);

  const t = useCallback(
    (key: string, fallback?: string): string => {
      return dict[lang][key] ?? dict["EN"][key] ?? fallback ?? key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside <LanguageProvider>");
  return ctx;
}
